# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 无声告白
author: 刘文壮
email: liu1114589929@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  不定期分享一些日常开发中遇到的问题及解决方案，大部分和前端开发相关，如Angular、Vue、React等前端框架，
  也会有些诸如如git、VSCode等开发工具的相关知识。
  Aperiodically share some questions and anwsers in daily develop, almost releate to
  frontend develop, eg. Angular, Vue, React. Develop tools like git, VSCode will also touch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: liuwenzhuang
github_username: liuwenzhuang
codepen_username: liuwenzhuang
csdn_usercode: u010730126

google_analytics: G-QJ85M6F5B2

github:
  url: http://liuwenzhuang.github.io/

repository: liuwenzhuang/liuwenzhuang.github.io

# Build settings
markdown: kramdown
#theme: minima
#sass:
#  style: compressed #minify css

paginate: 9
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
