# Site settings
title: Newbie's Blogs
email: liu1114589929@gmail.com
description: >
  Ionic1及Ionic2学习笔记，记录从学习初期跟着文档亦步亦趋的时期，记录从学习中期跟着诸多大神学习扩展的时期，记录现在半斤八两的迷茫与惆怅。现在依然跟着大神在走，不时记录两笔，不值一提，仅作为笔记吧。
baseurl: ""
url: ""
urlPrefix: http://liuwenzhuang.github.io
fixedNav: 'true' # true or false
theme: blue # green, blue, orange, purple, grey
twitterUsername: liuwenzhuang
githubUsername: liuwenzhuang
codepenUsername: liuwenzhuang

comments:
    disqus: "liuwenzhuang"
#    isso: "comments.mysite.org"

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site]
sass:
  style: compressed #minify css

#paginate: 10
#gems: [jekyll-paginate]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      categories: ['ionic', 'angular']
